/* portfolio-data.js — generated by Portfolio Admin on 04/07/2026
 * Edit via admin/index.html → Export → replace this file → commit & push
 */
window.PORTFOLIO_DATA = {

  experience: [
    {
      id: "exp1",
      logo: "img/l3m_holding_logo.jpg",
      logoAlt: "L3M logo",
      org: "L3M",
      en: { when: "2026", role: "Internship – QA Tester Web/Mobile", det: "Functional, regression and security testing on web and mobile applications. Writing test plans, test cases and bug reports; collaboration with development teams in an agile cycle." },
      fr: { when: "2026", role: "Stage – Testeur QA Web/Mobile", det: "Réalisation de tests fonctionnels, de régression et de sécurité sur des applications web et mobiles. Rédaction de plans et cas de test et rapports de bugs ; collaboration avec les équipes de développement en cycle agile." }
    },
    {
      id: "exp2",
      logo: "",
      logoAlt: "",
      org: "Ensate International Students CLUB",
      en: { when: "Feb. 2026 – Present", role: "Secretary General", det: "Managing administrative operations, communication and logistics for major events of the international student association at ENSA Tétouan." },
      fr: { when: "Fév. 2026 – Présent", role: "Secrétaire Général", det: "Gestion des opérations administratives, de la communication et de la logistique pour les événements majeurs de l'association internationale d'étudiants de l'ENSA Tétouan." }
    },
    {
      id: "exp3",
      logo: "img/aiesec.png",
      logoAlt: "AIESEC logo",
      org: "AIESEC in Tangier",
      en: { when: "02/2025 – 07/2025", role: "EP Manager – OGX-OGT", det: "AIESEC is a global youth-led organization focused on leadership development through international exchanges. As an Experience Participant (EP) Manager for Outgoing Global Talent, I managed and coordinated international internship programs, helping young professionals secure impactful opportunities abroad." },
      fr: { when: "02/2025 – 07/2025", role: "Responsable EP – OGX-OGT", det: "L'AIESEC est une organisation mondiale dirigée par des jeunes axée sur le développement du leadership par des échanges internationaux. En tant que Responsable EP pour les Talents Mondiaux Sortants, j'ai géré et coordonné des programmes de stages internationaux, aidant de jeunes professionnels à décrocher des opportunités impactantes à l'étranger." }
    },
    {
      id: "exp4",
      logo: "img/brainwave.jpg",
      logoAlt: "Brainwave Matrix logo",
      org: "Brainwave Matrix",
      en: { when: "Apr. – May 2025", role: "Internship – Cybersecurity &amp; ML", det: "Built a Phishing URL Scanner (Python, Flask, Scikit-learn) classifying URLs in real time, and a Password Strength Checker (Python, Streamlit) with visual feedback and improvement suggestions." },
      fr: { when: "Avr. – Mai 2025", role: "Stage – Cybersécurité &amp; ML", det: "Développement d'un Scanner d'URLs de Phishing (Python, Flask, Scikit-learn) classifiant les URLs en temps réel, et d'un Vérificateur de Force de Mot de Passe (Python, Streamlit) avec retour visuel et suggestions d'amélioration." }
    },
    {
      id: "exp5",
      logo: "img/odace.jpg",
      logoAlt: "O'dace logo",
      org: "O'dace",
      en: { when: "01/2025 – 05/2025", role: "Club CoderSphere", det: "CoderSphere is a technology hub dedicated to robotics, embedded systems, and cybersecurity. Through hands-on projects, I deepened my expertise in electronics and hardware design while strengthening my technical problem-solving and teamwork skills in a collaborative environment." },
      fr: { when: "01/2025 – 05/2025", role: "Club CoderSphere", det: "CoderSphere est un hub technologique dédié à la robotique, aux systèmes embarqués et à la cybersécurité. À travers des projets pratiques, j'ai approfondi mon expertise en électronique et en conception matérielle tout en renforçant mes compétences en résolution de problèmes techniques dans un environnement collaboratif." }
    },
    {
      id: "exp6",
      logo: "img/aebm.jpg",
      logoAlt: "AEBM logo",
      org: "AEBM – Tétouan",
      en: { when: "10/2023 – 10/2024", role: "Deputy Secretary General", det: "The AEBM supports Burkinabé students in Morocco through integration and guidance. During my tenure as Deputy Secretary General, I oversaw administrative tasks and coordinated community projects, significantly enhancing my leadership, organizational, and cross-cultural communication abilities." },
      fr: { when: "10/2023 – 10/2024", role: "Secrétaire Général Adjoint", det: "L'AEBM soutient les étudiants Burkinabés au Maroc à travers l'intégration et l'orientation. En tant que Secrétaire Général Adjoint, j'ai supervisé les tâches administratives et coordonné des projets communautaires, renforçant mes capacités de leadership, d'organisation et de communication interculturelle." }
    }
  ],

  services: [
    {
      id: "sv1",
      color: "red",
      iconSvg: "<path d=\"M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z\"/><circle cx=\"12\" cy=\"11\" r=\"3\"/>",
      tags: [
  "Kali Linux",
  "OWASP",
  "Metasploit"
],
      en: { title: "Penetration Testing", desc: "Real-world attack simulation on your systems to uncover vulnerabilities before malicious actors can exploit them." },
      fr: { title: "Test de Pénétration", desc: "Simulation d'attaques réelles sur vos systèmes pour identifier les vulnérabilités avant les acteurs malveillants." }
    },
    {
      id: "sv2",
      color: "blue",
      iconSvg: "<rect x=\"2\" y=\"3\" width=\"20\" height=\"14\" rx=\"2\"/><path d=\"M8 21h8M12 17v4\"/><path d=\"M7 10l2 2 3-3 2 2 2-2\"/>",
      tags: [
  "Wazuh",
  "TheHive 5",
  "Shuffle SOAR"
],
      en: { title: "SOC &amp; Blue Team", desc: "Full SOC infrastructure deployment (SIEM, SOAR, incident management) to detect and respond to threats in real time." },
      fr: { title: "SOC &amp; Blue Team", desc: "Déploiement d'infrastructure SOC complète (SIEM, SOAR, gestion d'incidents) pour détecter et répondre aux menaces en temps réel." }
    },
    {
      id: "sv3",
      color: "purple",
      iconSvg: "<circle cx=\"11\" cy=\"11\" r=\"8\"/><path d=\"M21 21l-4.35-4.35\"/><path d=\"M8 11l2 2 4-4\"/>",
      tags: [
  "QA Testing",
  "Burp Suite",
  "Agile"
],
      en: { title: "Security &amp; Web/Mobile Testing", desc: "Functional, regression and security testing on your web and mobile apps, with structured bug reports in an agile cycle." },
      fr: { title: "Sécurité &amp; Tests Web/Mobile", desc: "Tests fonctionnels, de régression et de sécurité sur vos applications web et mobiles, avec rapports de bugs en cycle agile." }
    },
    {
      id: "sv4",
      color: "green",
      iconSvg: "<polyline points=\"16 18 22 12 16 6\"/><polyline points=\"8 6 2 12 8 18\"/>",
      tags: [
  "HTML/CSS",
  "JavaScript",
  "React"
],
      en: { title: "Front-End Development", desc: "Modern, responsive and animated web interfaces — from mockup to deployment, with a strong focus on UX quality." },
      fr: { title: "Développement Front-End", desc: "Interfaces web modernes, responsives et animées — de la maquette au déploiement, avec une attention particulière à l'UX." }
    },
    {
      id: "sv5",
      color: "orange",
      iconSvg: "<rect x=\"2\" y=\"3\" width=\"20\" height=\"14\" rx=\"2\"/><line x1=\"2\" y1=\"7\" x2=\"22\" y2=\"7\"/><path d=\"M8 21h8M12 17v4\"/>",
      tags: [
  "JavaFX",
  "MySQL",
  "JDBC"
],
      en: { title: "Java Desktop Apps", desc: "Full-featured desktop applications for client management, reservations or business workflows, connected to a database." },
      fr: { title: "Applications Desktop Java", desc: "Applications bureau complètes pour la gestion de clients, réservations ou workflows métier, connectées à une base de données." }
    },
    {
      id: "sv6",
      color: "amber",
      iconSvg: "<rect x=\"7\" y=\"7\" width=\"10\" height=\"10\" rx=\"1\"/><path d=\"M9 2v2M15 2v2M9 20v2M15 20v2M2 9h2M2 15h2M20 9h2M20 15h2\"/>",
      tags: [
  "ESP32",
  "Arduino",
  "FPGA",
  "VHDL"
],
      en: { title: "IoT &amp; Embedded Systems", desc: "Design of intelligent embedded systems: data acquisition, automation and IoT/cloud connectivity." },
      fr: { title: "IoT &amp; Systèmes Embarqués", desc: "Conception de systèmes embarqués intelligents : acquisition de données, automatisation et connectivité IoT/cloud." }
    },
    {
      id: "sv7",
      color: "sky",
      iconSvg: "<path d=\"M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9z\"/><rect x=\"10\" y=\"13\" width=\"4\" height=\"4\" rx=\"1\"/><path d=\"M12 13v-2a2 2 0 0 1 4 0v2\"/>",
      tags: [
  "Azure",
  "OCI",
  "Suricata",
  "VNet"
],
      en: { title: "Cloud Security &amp; IDS/IPS", desc: "Deployment and hardening of cloud infrastructures with active intrusion detection and prevention systems." },
      fr: { title: "Sécurité Cloud &amp; IDS/IPS", desc: "Déploiement et sécurisation d'infrastructures cloud avec systèmes de détection et prévention d'intrusions actifs." }
    },
    {
      id: "sv8",
      color: "violet",
      iconSvg: "<circle cx=\"5\" cy=\"7\" r=\"2\"/><circle cx=\"19\" cy=\"7\" r=\"2\"/><circle cx=\"5\" cy=\"17\" r=\"2\"/><circle cx=\"19\" cy=\"17\" r=\"2\"/><circle cx=\"12\" cy=\"12\" r=\"2\"/><path d=\"M7 7h3m4 0h3M7 17h3m4 0h3M12 14v2M12 10V8\"/>",
      tags: [
  "Python",
  "Scikit-learn",
  "Flask",
  "Streamlit"
],
      en: { title: "AI &amp; Machine Learning", desc: "ML models for classification, anomaly detection and predictive analytics applied to real-world problems." },
      fr: { title: "IA &amp; Machine Learning", desc: "Modèles ML pour la classification, la détection d'anomalies et l'analyse prédictive appliquée à des problèmes concrets." }
    }
  ],

  projects: [
    {
      id: "shadow",
      category: "cyber",
      detId: "shadow",
      title: "ShadowFactory – Red Team vs Blue Team",
      thumbnail: "img/img19.png",
      thumbAlt: "ShadowFactory SOC",
      stack: [
  "OCI",
  "Wazuh",
  "TheHive 5",
  "Shuffle SOAR",
  "Modbus",
  "iptables"
],
      github: "https://github.com/Pro-simpo",
      en: { cats: "Cybersecurity &middot; SOC &middot; Cloud &middot; R&amp;D", desc: "Full SOC infrastructure (Wazuh, TheHive 5, Shuffle SOAR) on OCI monitoring a simulated IT/OT industrial environment. 15 detection rules, automated SOAR workflow (detect → block IP → TheHive incident)." },
      fr: { cats: "Cybersécurité &middot; SOC &middot; Cloud &middot; R&amp;D", desc: "Infrastructure SOC complète (Wazuh, TheHive 5, Shuffle SOAR) sur OCI pour surveiller un environnement IT/OT simulant un site industriel. 15 règles de détection, workflow SOAR automatisé (détection → blocage IP → incident TheHive)." }
    },
    {
      id: "ids",
      category: "cyber",
      detId: "ids",
      title: "IDS/IPS Cloud Deployment (Azure)",
      thumbnail: "img/img19.png",
      thumbAlt: "IDS/IPS Azure",
      stack: [
  "Azure",
  "Suricata 8.0.4",
  "VNet",
  "NSG",
  "IDS/IPS"
],
      github: "https://github.com/Pro-simpo",
      en: { cats: "Cybersecurity &middot; IDS/IPS &middot; Azure", desc: "Suricata 8.0.4 deployment on Azure with custom VNet segmentation and NSG rules. 50,000+ active signatures and 4 custom detection rules for intrusion prevention." },
      fr: { cats: "Cybersécurité &middot; IDS/IPS &middot; Azure", desc: "Déploiement de Suricata 8.0.4 sur Azure avec segmentation VNet personnalisée et règles NSG. Plus de 50 000 signatures actives et 4 règles de détection sur mesure pour la prévention d'intrusions." }
    },
    {
      id: "fire",
      category: "iot",
      detId: "fire",
      title: "Forest Fire Detection System",
      thumbnail: "img/videoFireDetection.jpg",
      thumbAlt: "Forest Fire Detection",
      stack: [
  "ESP32",
  "MQTT",
  "Python",
  "Scikit-learn",
  "Flask",
  "MySQL"
],
      github: "https://github.com/KunakaDK/Proactive-Forest-Fire-Detection-Management-System",
      en: { cats: "IoT &middot; Embedded &middot; ML", desc: "End-to-end IoT solution combining ESP32 sensors, Random Forest ML, and a real-time web dashboard for early forest fire detection." },
      fr: { cats: "IoT &middot; Embarqué &middot; ML", desc: "Solution IoT complète combinant des capteurs ESP32, un classificateur Random Forest et un tableau de bord web en temps réel pour la détection précoce des feux de forêt." }
    },
    {
      id: "solar",
      category: "iot",
      detId: "solar",
      title: "Solar Tracker AI-Driven System",
      thumbnail: "img/solar.jpg",
      thumbAlt: "Solar Tracker",
      stack: [
  "ESP32",
  "Arduino",
  "Flutter",
  "Firebase",
  "AI/ML"
],
      github: "https://github.com/Pro-simpo/",
      en: { cats: "IoT &middot; AI &middot; Embedded", desc: "Embedded system with ESP32 and AI algorithms that automatically adjusts solar panel orientation to maximize energy production." },
      fr: { cats: "IoT &middot; IA &middot; Embarqué", desc: "Système embarqué avec ESP32 et algorithmes IA qui ajuste automatiquement l'orientation des panneaux solaires pour maximiser la production d'énergie." }
    },
    {
      id: "hepras",
      category: "java",
      detId: "hepras",
      title: "HePRAS Healthcare System",
      thumbnail: "img/videoHePRAS.jpg",
      thumbAlt: "HePRAS",
      stack: [
  "Java Swing",
  "Oracle DB 21c",
  "JDBC",
  "SHA-256"
],
      github: "https://github.com/KunakaDK/Healthcare-Patient-Records-and-Analytics-System-HePRAS-",
      en: { cats: "Java &middot; Database", desc: "Database management app for medical practices — patient records, appointments, billing, and role-based access control with SHA-256." },
      fr: { cats: "Java &middot; Base de données", desc: "Application de gestion médicale — dossiers patients, rendez-vous, facturation et contrôle d'accès basé sur les rôles avec SHA-256." }
    },
    {
      id: "fpga",
      category: "fpga",
      detId: "fpga",
      title: "Intelligent Parking System",
      thumbnail: "img/videoFPGA.jpg",
      thumbAlt: "FPGA Parking",
      stack: [
  "VHDL",
  "FPGA",
  "FSM",
  "50 MHz"
],
      github: "https://github.com/KunakaDK/Intelligent_Parking_System_with_VHDL",
      en: { cats: "FPGA &middot; VHDL &middot; Digital Design", desc: "FPGA-based parking management with automated barrier control, real-time occupancy display, and FSM logic deployed in VHDL." },
      fr: { cats: "FPGA &middot; VHDL &middot; Conception numérique", desc: "Gestion de parking à base de FPGA avec contrôle automatique des barrières, affichage de l'occupation en temps réel et logique FSM déployée en VHDL." }
    },
    {
      id: "job",
      category: "web",
      detId: "job",
      title: "React Job Application Tracker",
      thumbnail: "img/videoJobApplication.png",
      thumbAlt: "Job Tracker",
      stack: [
  "React",
  "Context API",
  "Recharts"
],
      github: "https://github.com/Pro-simpo/REACT_Job_Application_Tracker",
      en: { cats: "Web &middot; React", desc: "React app to manage job applications with an analytics dashboard, advanced search/filter, and JSON import/export features." },
      fr: { cats: "Web &middot; React", desc: "Application React pour gérer les candidatures d'emploi avec tableau de bord analytique, recherche/filtre avancé et fonctionnalités d'import/export JSON." }
    },
    {
      id: "brainwave",
      category: "cyber",
      detId: "brainwave",
      title: "Brainwave Internship Projects",
      thumbnail: "img/brainwave.jpg",
      thumbAlt: "Brainwave Internship",
      stack: [
  "Python",
  "Flask",
  "Streamlit",
  "Scikit-learn"
],
      github: "https://github.com/Pro-simpo/Brainwave_Matrix_Intern",
      en: { cats: "Cybersecurity &middot; Python &middot; ML", desc: "Two security tools built during internship: a Phishing URL Scanner with ML classification and a Password Strength Checker following OWASP standards." },
      fr: { cats: "Cybersécurité &middot; Python &middot; ML", desc: "Deux outils de sécurité développés lors du stage : un Scanner d'URLs de Phishing avec classification ML et un Vérificateur de Force de Mot de Passe selon les normes OWASP." }
    },
    {
      id: "agency",
      category: "java",
      detId: "agency",
      title: "Travel Agency Management System",
      thumbnail: "img/img19.png",
      thumbAlt: "Travel Agency App",
      stack: [
  "Java",
  "JavaFX",
  "MySQL",
  "JDBC"
],
      github: "https://github.com/Pro-simpo",
      en: { cats: "Java &middot; JavaFX &middot; Database", desc: "Desktop app for managing clients, reservations, itineraries, and payments — with admin dashboard and WhatsApp integration." },
      fr: { cats: "Java &middot; JavaFX &middot; Base de données", desc: "Application bureau pour la gestion des clients, réservations, itinéraires et paiements — avec tableau de bord admin et intégration WhatsApp." }
    },
    {
      id: "portfolio",
      category: "web",
      detId: "portfolio",
      title: "This Portfolio",
      thumbnail: "img/port1.png",
      thumbAlt: "Portfolio screenshot",
      stack: [
  "HTML",
  "CSS",
  "JavaScript",
  "Canvas"
],
      github: "https://github.com/Pro-simpo",
      en: { cats: "Web &middot; Front-end", desc: "This portfolio — built from scratch with vanilla HTML, CSS, and JavaScript. Dark/light themes, canvas animations, and fully responsive." },
      fr: { cats: "Web &middot; Front-end", desc: "Ce portfolio — construit de zéro avec HTML, CSS et JavaScript vanilla. Thèmes sombre/clair, animations canvas et entièrement responsive." }
    },
    {
      id: "odace",
      category: "iot",
      detId: "odace",
      title: "O'dace Electronics Projects",
      thumbnail: "img/odace1.jpg",
      thumbAlt: "O'dace projects",
      stack: [
  "Arduino",
  "C++",
  "Electronics"
],
      github: "https://github.com/Pro-simpo",
      en: { cats: "IoT &middot; Electronics &middot; Arduino", desc: "Hands-on Arduino and electronics projects in the O'dace club — components, circuits, and applied embedded systems theory." },
      fr: { cats: "IoT &middot; Électronique &middot; Arduino", desc: "Projets Arduino et électronique pratiques au club O'dace — composants, circuits et théorie des systèmes embarqués appliquée." }
    },
    {
      id: "marathon",
      category: "web",
      detId: "marathon",
      title: "CoderSphere Coding Marathons",
      thumbnail: "img/marathon1-1.png",
      thumbAlt: "Marathon 1 screenshot",
      stack: [
  "HTML",
  "CSS"
],
      github: "https://github.com/Pro-simpo",
      en: { cats: "Web &middot; HTML &middot; CSS", desc: "Two timed front-end coding challenges. Won Marathon 1 by delivering a complete website in 5 hours. Placed 3rd in Marathon 2." },
      fr: { cats: "Web &middot; HTML &middot; CSS", desc: "Deux défis de programmation front-end chronométrés. Marathon 1 remporté en livrant un site complet en 5 heures. 3ème place au Marathon 2." }
    },
    {
      id: "engineering",
      category: "autre",
      detId: "engineering",
      title: "Engineering Cycle Projects",
      thumbnail: "img/img19.png",
      thumbAlt: "Engineering projects",
      stack: [
  "C",
  "Python",
  "VHDL",
  "Network"
],
      github: "https://github.com/Pro-simpo",
      en: { cats: "Academic &middot; Engineering", desc: "Academic projects from the engineering cycle at ENSA Tetouan combining cybersecurity and embedded systems across various modules." },
      fr: { cats: "Académique &middot; Ingénierie", desc: "Projets académiques du cycle ingénieur à l'ENSA Tétouan combinant cybersécurité et systèmes embarqués à travers différents modules." }
    },
    {
      id: "preparatory",
      category: "autre",
      detId: "preparatory",
      title: "Preparatory Cycle Project",
      thumbnail: "img/prepa1.jpg",
      thumbAlt: "Preparatory project",
      stack: [
  "Teamwork",
  "Community",
  "Leadership"
],
      github: "https://github.com/Pro-simpo",
      en: { cats: "Community &middot; Social", desc: "Team social project: renovated an orphanage study room, organized tutoring sessions, and raised 6,500 MAD in community funding." },
      fr: { cats: "Communauté &middot; Social", desc: "Projet social en équipe : rénovation d'une salle d'étude dans un orphelinat, sessions de tutorat et collecte de 6 500 MAD." }
    }
  ],

  skills: [
    {
      id: "cat1",
      containerClass: "body1",
      i18nKey: "skills-cat1",
      items: [
        { name: "Penetration testing", iconClass: "fa-solid fa-user-secret ibadge" },
        { name: "Security testing", iconClass: "fa-solid fa-shield-halved ibadge" },
        { name: "Computer networking", iconClass: "fa-solid fa-network-wired ibadge" },
        { name: "Malware analysis", iconClass: "fa-solid fa-bug-slash ibadge" },
        { name: "Kali Linux", iconClass: "fa-solid fa-terminal ibadge" },
        { name: "Wazuh", iconClass: "fa-solid fa-eye ibadge" },
        { name: "TheHive", iconClass: "fa-solid fa-bug ibadge" },
        { name: "Suricata", iconClass: "fa-solid fa-tower-broadcast ibadge" },
        { name: "Burp Suite", iconClass: "fa-solid fa-magnifying-glass ibadge" },
        { name: "Metasploit", iconClass: "fa-solid fa-crosshairs ibadge" },
        { name: "SIEM", iconClass: "fa-solid fa-chart-line ibadge" },
        { name: "iptables", iconClass: "fa-solid fa-fire-flame-curved ibadge" }
      ]
    },
    {
      id: "cat2",
      containerClass: "body2",
      i18nKey: "skills-cat2",
      items: [
        { name: "FPGA", iconClass: "fa-solid fa-microchip ibadge" },
        { name: "VHDL", iconClass: "fa-solid fa-file-code ibadge" },
        { name: "Verilog", iconClass: "fa-solid fa-file-code ibadge" },
        { name: "ESP32", iconClass: "fa-solid fa-microchip ibadge" },
        { name: "Arduino", iconClass: "fa-brands fa-usb ibadge" },
        { name: "Circuits design", iconClass: "fa-solid fa-draw-polygon ibadge" },
        { name: "MQTT", iconClass: "fa-solid fa-wifi ibadge" },
        { name: "Modbus", iconClass: "fa-solid fa-plug ibadge" },
        { name: "Raspberry Pi", iconClass: "fa-brands fa-raspberry-pi ibadge" }
      ]
    },
    {
      id: "cat3",
      containerClass: "body3",
      i18nKey: "skills-cat3",
      items: [
        { name: "JavaScript", iconClass: "fa-brands fa-js skill-icon ibadge" },
        { name: "ReactJs", iconClass: "fa-brands fa-react skill-icon ibadge" },
        { name: "HTML 5", iconClass: "fa-brands fa-html5 skill-icon ibadge" },
        { name: "CSS 3", iconClass: "fa-brands fa-css3-alt skill-icon ibadge" },
        { name: "Python", iconClass: "fa-brands fa-python skill-icon ibadge" },
        { name: "Java", iconClass: "fa-brands fa-java skill-icon ibadge" },
        { name: "C", iconClass: "fa-solid fa-c skill-icon ibadge" },
        { name: "Flask", iconClass: "fa-solid fa-flask ibadge" },
        { name: "Scikit-learn", iconClass: "fa-solid fa-brain ibadge" },
        { name: "MySQL", iconClass: "fa-solid fa-database ibadge" },
        { name: "JavaFX", iconClass: "fa-brands fa-java ibadge" },
        { name: "Git", iconClass: "fa-brands fa-git-alt ibadge" },
        { name: "Streamlit", iconClass: "fa-solid fa-chart-bar ibadge" }
      ]
    },
    {
      id: "cat4",
      containerClass: "body4",
      i18nKey: "skills-cat4",
      items: [
        { name: "Figma", iconClass: "fa-brands fa-figma skill-icon ibadge" },
        { name: "Canva", iconClass: "fa-solid fa-pen-ruler ibadge" },
        { name: "MS Suite", iconClass: "fa-brands fa-microsoft ibadge" },
        { name: "Windows", iconClass: "fa-brands fa-windows skill-icon ibadge" },
        { name: "Linux", iconClass: "fa-brands fa-linux skill-icon ibadge" },
        { name: "discipline", iconClass: "fa-solid fa-bullseye ibadge" },
        { name: "leadership", iconClass: "fa-solid fa-people-group ibadge" },
        { name: "management", iconClass: "fa-solid fa-sitemap ibadge" },
        { name: "QA Testing", iconClass: "fa-solid fa-clipboard-check ibadge" },
        { name: "Agile", iconClass: "fa-solid fa-rotate ibadge" },
        { name: "Azure", iconClass: "fa-solid fa-cloud ibadge" },
        { name: "OCI", iconClass: "fa-solid fa-server ibadge" },
        { name: "GitHub", iconClass: "fa-brands fa-github ibadge" }
      ]
    }
  ],

  certificates: [
    { id: "cert-cc", pdf: "certificates/CC.pdf", thumb: "img/CC.jpg", thumbAlt: "ISC2 CC", code: "ISC² · CC", title: "Certified in Cybersecurity", issuer: "ISC²" },
    { id: "cert-cisco", pdf: "certificates/cisco_ethical_hacker.pdf", thumb: "img/cisco_ethical_hacker.jpeg", thumbAlt: "Cisco Ethical Hacker", code: "CISCO · EH", title: "Ethical Hacker", issuer: "Cisco" },
    { id: "cert-alison", pdf: "certificates/Alison_certificate_cyber_security__understand_threats_and_prevent_attacks.pdf", thumb: "img/cybersecurity.png", thumbAlt: "Cybersecurity", code: "ALISON · CYBER", title: "Cybersecurity: Understand Threats &amp; Prevent Attacks", issuer: "Alison" },
    { id: "cert-ia", pdf: "certificates/Certificat en Intelligence Artificielle.pdf", thumb: "img/intelligence artificielle.png", thumbAlt: "Intelligence Artificielle", code: "IA · CERT", title: "Artificial Intelligence Certificate", issuer: "Formation IA" },
    { id: "cert-html", pdf: "certificates/Learner-Verification-HTML5_CSS3_JS.pdf", thumb: "img/HTML5_CSS3_JS.pdf.png", thumbAlt: "Web Development", code: "WEB · DEV", title: "HTML5 · CSS3 · JavaScript", issuer: "Learner Verification" },
    { id: "cert-hack", pdf: "certificates/Ethical_Hacking.pdf", thumb: "img/hacking.png", thumbAlt: "Ethical Hacking", code: "SEC · HACK", title: "Ethical Hacking", issuer: "Certification" },
    { id: "cert-google", pdf: "certificates/Cours sur la citoyenneté numérique et la sécurité _ Google.pdf", thumb: "img/citoyennete.png", thumbAlt: "Google Digital Citizenship", code: "GOOGLE · DIGITAL", title: "Digital Citizenship &amp; Security", issuer: "Google" },
    { id: "cert-ml", pdf: "certificates/certificate machine learning.pdf", thumb: "img/machine.png", thumbAlt: "Machine Learning", code: "ML · CERT", title: "Machine Learning", issuer: "Certification" },
    { id: "cert-canva", pdf: "certificates/Alison_certificate_how_to_design_with_canva.pdf", thumb: "img/design.png", thumbAlt: "Design with Canva", code: "ALISON · DESIGN", title: "How to Design with Canva", issuer: "Alison" },
    { id: "cert-forcen_cyber", pdf: "certificates/Taobata_forcen_cybersecurity.pdf", thumb: "img/forcen_cyber.jpg", thumbAlt: "Analyste Junior en Cybersecutité par Forcen Sénégal", code: "Forcen · Cybersecurity", title: "Analyste Junior en Cybersecutité", issuer: "Forcen Sénégal" }
  ]

};
